vacuum_living_room:
  alias: "Vacuum Living Room"
  sequence:
    - service: vacuum.send_command
      data:
        entity_id: vacuum.xiaomi_vacuum_cleaner
        command: app_zoned_clean
        params: [[19516,24058,22666,28908,1]]
