vacuum_kitchen:
  alias: "Vacuum Kitchen"
  sequence:
    - service: vacuum.send_command
      data:
        entity_id: vacuum.xiaomi_vacuum_cleaner
        command: app_zoned_clean
        params: [[23131,26748,25531,29148,1]]
