vacuum_bathroom:
  alias: "Vacuum Bathroom"
  sequence:
    - service: vacuum.send_command
      data:
        entity_id: vacuum.xiaomi_vacuum_cleaner
        command: app_zoned_clean
        params: [[21667,31620,23117,33470,1]]
